import { Request, Response } from 'express';
import prisma from '../config/database';
import { z } from 'zod';

// Validation schema for creating a patient
const createPatientSchema = z.object({
  fullName: z.string().min(2, 'Full name must be at least 2 characters'),
  phone: z.string().optional(),
  age: z.number().min(0).max(150).optional(),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER']).optional(),
});

// Create a new patient (Doctor only)
export const createPatient = async (req: Request, res: Response): Promise<void> => {
  try {
    const doctorId = (req as any).user.id;

    // Validate input
    const validatedData = createPatientSchema.parse(req.body);

    // Get doctor details to check trial limits
    const doctor = await prisma.doctor.findUnique({
      where: { id: doctorId },
      select: {
        id: true,
        subscriptionStatus: true,
        patientsCreated: true,
        trialEndsAt: true,
        status: true,
      },
    });

    if (!doctor) {
      res.status(404).json({
        success: false,
        message: 'Doctor not found',
      });
      return;
    }

    if (doctor.status !== 'VERIFIED') {
      res.status(403).json({
        success: false,
        message: 'Your account must be verified to create patients',
      });
      return;
    }

    // Check trial limits
    if (doctor.subscriptionStatus === 'TRIAL') {
      // Check if trial has expired
      if (new Date() > new Date(doctor.trialEndsAt)) {
        res.status(403).json({
          success: false,
          message: 'Your trial period has expired. Please subscribe to continue creating patients.',
          trialExpired: true,
        });
        return;
      }

      // Check patient limit (max 2 during trial)
      if (doctor.patientsCreated >= 2) {
        res.status(403).json({
          success: false,
          message: 'Trial limit reached. You can create maximum 2 patients during trial. Please subscribe to create more patients.',
          trialLimitReached: true,
        });
        return;
      }
    }

    // Check if subscription is expired
    if (doctor.subscriptionStatus === 'EXPIRED') {
      res.status(403).json({
        success: false,
        message: 'Your subscription has expired. Please renew to create patients.',
        subscriptionExpired: true,
      });
      return;
    }

    // Create the patient
    const patient = await prisma.patient.create({
      data: {
        fullName: validatedData.fullName,
        phone: validatedData.phone,
        age: validatedData.age,
        gender: validatedData.gender,
        doctorId: doctorId,
        // accessToken is auto-generated by Prisma (uuid)
      },
      select: {
        id: true,
        fullName: true,
        phone: true,
        age: true,
        gender: true,
        accessToken: true,
        createdAt: true,
      },
    });

    // Increment doctor's patients count
    await prisma.doctor.update({
      where: { id: doctorId },
      data: {
        patientsCreated: {
          increment: 1,
        },
      },
    });

    // Generate shareable link
    const shareableLink = `${process.env.FRONTEND_URL || 'http://localhost:3002'}/p/${patient.accessToken}`;

    res.status(201).json({
      success: true,
      message: 'Patient created successfully',
      data: {
        patient,
        shareableLink,
      },
    });
  } catch (error: any) {
    console.error('Create patient error:', error);

    if (error.name === 'ZodError') {
      res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: error.errors,
      });
    } else {
      res.status(500).json({
        success: false,
        message: 'Error creating patient',
        error: error.message,
      });
    }
  }
};

// Get all patients for a doctor
export const getDoctorPatients = async (req: Request, res: Response): Promise<void> => {
  try {
    const doctorId = (req as any).user.id;
    const { search, page = 1, limit = 10 } = req.query;

    const where: any = {
      doctorId: doctorId,
    };

    if (search) {
      where.OR = [
        { fullName: { contains: search as string, mode: 'insensitive' } },
        { phone: { contains: search as string } },
      ];
    }

    const pageNum = parseInt(page as string);
    const limitNum = parseInt(limit as string);
    const skip = (pageNum - 1) * limitNum;

    const [patients, total] = await Promise.all([
      prisma.patient.findMany({
        where,
        select: {
          id: true,
          fullName: true,
          phone: true,
          age: true,
          gender: true,
          accessToken: true,
          createdAt: true,
          _count: {
            select: {
              consultations: true,
            },
          },
        },
        orderBy: { createdAt: 'desc' },
        skip,
        take: limitNum,
      }),
      prisma.patient.count({ where }),
    ]);

    // Add shareable link to each patient
    const patientsWithLinks = patients.map((patient) => ({
      ...patient,
      shareableLink: `${process.env.FRONTEND_URL || 'http://localhost:3002'}/p/${patient.accessToken}`,
    }));

    res.status(200).json({
      success: true,
      data: {
        patients: patientsWithLinks,
        pagination: {
          page: pageNum,
          limit: limitNum,
          total,
          totalPages: Math.ceil(total / limitNum),
        },
      },
    });
  } catch (error: any) {
    console.error('Get doctor patients error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching patients',
      error: error.message,
    });
  }
};

// Get patient details by ID (for doctor)
export const getPatientById = async (req: Request, res: Response): Promise<void> => {
  try {
    const doctorId = (req as any).user.id;
    const { patientId } = req.params;

    const patient = await prisma.patient.findFirst({
      where: {
        id: patientId,
        doctorId: doctorId, // Ensure doctor can only access their own patients
      },
      select: {
        id: true,
        fullName: true,
        phone: true,
        age: true,
        gender: true,
        accessToken: true,
        createdAt: true,
        updatedAt: true,
        consultations: {
          select: {
            id: true,
            status: true,
            startedAt: true,
            completedAt: true,
            chiefComplaint: true,
          },
          orderBy: { startedAt: 'desc' },
          take: 10,
        },
        vitals: {
          select: {
            id: true,
            weight: true,
            height: true,
            bloodPressure: true,
            temperature: true,
            heartRate: true,
            oxygenLevel: true,
            notes: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'desc' },
          take: 5,
        },
        medicalUploads: {
          select: {
            id: true,
            fileName: true,
            fileType: true,
            description: true,
            filePath: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'desc' },
        },
      },
    });

    if (!patient) {
      res.status(404).json({
        success: false,
        message: 'Patient not found',
      });
      return;
    }

    const shareableLink = `${process.env.FRONTEND_URL || 'http://localhost:3002'}/p/${patient.accessToken}`;

    res.status(200).json({
      success: true,
      data: {
        patient: {
          ...patient,
          shareableLink,
        },
      },
    });
  } catch (error: any) {
    console.error('Get patient by ID error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching patient details',
      error: error.message,
    });
  }
};

// Get patient details by access token (for patient access - no auth required)
export const getPatientByToken = async (req: Request, res: Response): Promise<void> => {
  try {
    const { token } = req.params;

    const patient = await prisma.patient.findUnique({
      where: { accessToken: token },
      select: {
        id: true,
        fullName: true,
        phone: true,
        age: true,
        gender: true,
        createdAt: true,
        doctor: {
          select: {
            id: true,
            fullName: true,
            specialization: true,
            phone: true,
            email: true,
            profilePhoto: true,
            upiId: true,
            qrCodeImage: true,
          },
        },
        consultations: {
          select: {
            id: true,
            status: true,
            startedAt: true,
            completedAt: true,
            chiefComplaint: true,
            prescription: {
              select: {
                id: true,
                diagnosis: true,
                medications: true,
                instructions: true,
                pdfPath: true,
                createdAt: true,
              },
            },
            paymentConfirmation: {
              select: {
                id: true,
                amount: true,
                confirmedByDoctor: true,
                confirmedAt: true,
              },
            },
          },
          orderBy: { startedAt: 'desc' },
        },
        vitals: {
          select: {
            id: true,
            weight: true,
            height: true,
            bloodPressure: true,
            temperature: true,
            heartRate: true,
            oxygenLevel: true,
            notes: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'desc' },
          take: 5,
        },
      },
    });

    if (!patient) {
      res.status(404).json({
        success: false,
        message: 'Patient not found. Please check the link.',
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: { patient },
    });
  } catch (error: any) {
    console.error('Get patient by token error:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching patient details',
      error: error.message,
    });
  }
};
